### ISSUE TITLE
[ATTENTION] SSP program and tainted mods (may) have malware, reported by virustotal.com services

### ISSUE THREAD

**Issue by ribbybbir** [nikolat/ukagaka-simultaneous-interpreter#1]
According to virustotal.com's report (of both file and URL address), Sakura Script Player (SSP), is said to contain malware. Mods that interact with the program, will risk malware infection. If you don't believe me, you can test virustotal.com for yourselves. Just make sure to use the Reanalyze function for your own scan.

It's also a shame that the ukagaka-simultaneous-interpreter is also infected as claimed by virustotal.com services (I expect its use would be in great demand). I suggest to first make a clean ukagaka mod that did not interact with SSP (use the virustotal.com test for assurance). Then switch ukagaka mod support to ninix-aya. At least with a Linux program, you get the chance to utilize the espeak program (default language is English). Of course, if you rather skip the computer voice, you can make your own espeak/vocal module. Don't forget to host mods on websites with HTTPS protocol.

I think that ukagaka malware that been going on for a bit too long.

Linux already have a ukagaka of its own. It's called vigor. Maybe the ukagaka development can learn from the vigor development.

---

In terms of the language translation service, maybe espeak or espeak-ng can help out (at least for vocal support). I am not sure if the terminal output be annoying, but progress gotta start somewhere. Here's the espeak-ng page for reference. I cannot guarantee human vocal packs from espeak-ng.
https://github.com/espeak-ng/espeak-ng
|
Things are too early for development before maintenance. We will just have to wait until then.

**Comment by nikolat** [comment]
I am sorry but I am not willing to maintain this repository.
Please read the [LICENSE](../blob/main/LICENSE) and feel free to fork it.

**Comment by Zichqec** [comment]
For anyone looking at this issue later with concerns:

This is a common and known false positive, because no virus scanning program is perfect. The [SSP homepage](http://ssp.shillest.net/) mentions this itself:

> VirusTotalをはじめとした一括ウイルススキャンサイトで、有害判定となる場合がありますが、技術的に完全なチェックソフトは存在しないことによる擬陽性ですので、安心してお使いください。
> 
> [毎日ClamAVで最新版をウイルススキャンしています](https://ssp.shillest.net/avscan.txt)

I have been a regular user of SSP for 7 years now, and I know several others who have been using it just as long, if not longer. None of us have ever had a problem with malware in it. If there was malware, the response from the community would be swift, as no ghost developer wants their users to be scared off by the program being dangerous.

The rest of the issue is a bit nonsensical as there aren't really "mods" in ukagaka, among other fundamental problems with what's being asked. Don't let this issue ruffle your feathers; if you're concerned, please reach out to [someone with actual knowledge of ukagaka](https://ukagakadreamteam.com/wiki/info/ukagaka_dream_team#where_to_find_us). (English link, since this issue is in English.)

**Comment by ribbybbir** [comment]
There is actually a way to remedy the damage. The ukagaka community can request for technical support in addressing and resolving any issues regarding false positives.

https://www.virustotal.com/gui/contact-us/

---

Funny that this Internet security, file and URL analyzer website's result pages are now not showing the Reanalyze button anymore.
